debezium.sink.type=rabbitmq
debezium.sink.rabbitmq.connection.host=rabbitmq
debezium.sink.rabbitmq.connection.username=guest
debezium.sink.rabbitmq.connection.password=guest

debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.database.hostname=postgres_db
debezium.source.database.port=5432
debezium.source.database.user=myuser
debezium.source.database.password=mypassword
debezium.source.database.dbname=mydatabase
debezium.source.topic.prefix=cdc_event